individualIds:
  - name: requests
    required: true
    in: query
    description: The array of batch requests
    schema:
      type: array
      items:
        type: object
        description: A stable Finch id (UUID v4) for an individual in the company. There is no limit to the number of individual_id to send per request. It is preferantial to send all ids in a single request for Finch to optimize provider rate-limits.
        required:
          - individual_id
        properties:
          individual_id:
            type: string 
            