openapi: 3.0.0
info:
  title: test
  version: '1.0'
  description: dfasdfsdfas
  contact:
    name: asdf
    url: sdfsadf
    email: sadfasf
  termsOfService: asdfasf
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
