---
openapi: 3.0.0
info:
  title: Finch API
  version: 2020-09-17
servers:
- url: https://api.tryfinch.com
paths:
  '/employer/company':
    $ref: './employer/_index.yaml#/company'
  '/employer/directory':
    $ref: './employer/_index.yaml#/directory'
  '/employer/individual':
    $ref: './employer/_index.yaml#/individual'
  '/employer/employment':
    $ref: './employer/_index.yaml#/employment'
  '/employer/payment':
    $ref: './employer/_index.yaml#/payment'
  '/employer/pay-statement':
    $ref: './employer/_index.yaml#/pay-statement'
